apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  # Internal ClusterIP allows the Frontend to communicate securely with Backend
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000        # The port cluster services use to talk to the backend
      targetPort: 5000  # The port inside the backend container
