apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  # NodePort to expose the frontend to internet traffic externally outside the Kubernetes cluster
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000       # Exposes the service on localhost:3000
      targetPort: 3000 # Directs to Nginx internal 3000 port
